packages:
  - playground
  - examples/*
  - packages/*
linkWorkspacePackages: 'deep'
ignoreWorkspaceRootCheck: true
strictPeerDependencies: true
allowBuilds:
  esbuild: false
  sharp: false
'overrides':
  'astrobook@*': 'workspace:*'
