import { glob, readFile, writeFile } from 'node:fs/promises'

import { getIconData, getIconsCSS } from '@iconify/utils'
import * as prettier from 'prettier'

const CLASS_PREFIX = 'astrobook-icon-'
const OUT_FILE = 'src/components/icon.css'
const SCAN_GLOB = 'src/**/*.{astro,ts,tsx,js,jsx}'

// The comment must not contain the scan glob: its "**/*" would end the CSS
// comment early ("*/") and break the file.
const HEADER = `/*
 * Generated by generate-icons.ts. Do not edit by hand.
 *
 * This file styles every \`astrobook-icon-{set}-{name}\` class found in the
 * source files under src/, using icon data from the installed @iconify-json
 * packages. To update it (after adding, removing, or renaming an icon class,
 * or after an @iconify-json version bump), run:
 *
 *   pnpm --filter @astrobook/ui generate-icons
 */

`

type IconSet = Parameters<typeof getIconData>[0]
type Resolution = { set: string; name: string } | { failure: string[] }

const setCache = new Map<string, IconSet | null>()

async function loadIconSet(set: string): Promise<IconSet | null> {
  let data = setCache.get(set)
  if (data === undefined) {
    try {
      const mod = (await import(`@iconify-json/${set}/icons.json`, {
        with: { type: 'json' },
      })) as { default: IconSet }
      data = mod.default
    } catch {
      data = null
    }
    setCache.set(set, data)
  }
  return data
}

// Set names can contain hyphens ('fluent-emoji'), so the set/name split is
// found by trying every prefix length. Exactly one installed set may contain
// the icon; zero or multiple matches return a failure description.
async function resolveToken(token: string): Promise<Resolution> {
  const segments = token.split('-')
  const tried: string[] = []
  const matches: { set: string; name: string }[] = []
  for (let i = 1; i < segments.length; i++) {
    const set = segments.slice(0, i).join('-')
    const name = segments.slice(i).join('-')
    const icons = await loadIconSet(set)
    if (!icons) {
      tried.push(`tried @iconify-json/${set} (not installed)`)
    } else if (getIconData(icons, name)) {
      matches.push({ set, name })
    } else {
      tried.push(
        `tried @iconify-json/${set} (installed, but has no icon "${name}")`,
      )
    }
  }
  if (matches.length === 1) return matches[0]
  if (matches.length > 1) {
    return {
      failure: [
        'ambiguous, more than one installed set matches:',
        ...matches.map((m) => `  @iconify-json/${m.set} has icon "${m.name}"`),
      ],
    }
  }
  return { failure: tried }
}

async function main() {
  const pattern = new RegExp(`${CLASS_PREFIX}([a-z0-9]+(?:-[a-z0-9]+)*)`, 'g')
  const exclude = (entry: string) =>
    entry.includes('node_modules') || entry.endsWith('icon.css')

  const tokenFiles = new Map<string, Set<string>>()
  for await (const file of glob(SCAN_GLOB, { exclude })) {
    const text = await readFile(file, 'utf8')
    for (const match of text.matchAll(pattern)) {
      const token = match[1]
      if (!tokenFiles.has(token)) tokenFiles.set(token, new Set())
      tokenFiles.get(token)?.add(file)
    }
  }

  const found = new Map<string, Set<string>>()
  const errors: string[] = []
  for (const token of [...tokenFiles.keys()].sort()) {
    const files = [...(tokenFiles.get(token) ?? [])].sort()
    const resolved = await resolveToken(token)
    if ('failure' in resolved) {
      errors.push(
        [
          `"${CLASS_PREFIX}${token}" (found in ${files.join(', ')})`,
          ...resolved.failure.map((line) => `  ${line}`),
        ].join('\n'),
      )
      continue
    }
    if (!found.has(resolved.set)) found.set(resolved.set, new Set())
    found.get(resolved.set)?.add(resolved.name)
  }

  if (errors.length > 0) {
    throw new Error(
      [
        `Cannot resolve ${errors.length} icon class(es):`,
        ...errors,
        'Fix the icon name, or adjust the installed @iconify-json/* packages',
        'in the devDependencies of packages/ui.',
      ].join('\n'),
    )
  }

  let css = HEADER
  for (const set of [...found.keys()].sort()) {
    const icons = await loadIconSet(set)
    if (!icons) continue
    css += getIconsCSS(icons, [...(found.get(set) ?? [])].sort(), {
      iconSelector: `.${CLASS_PREFIX}{prefix}-{name}`,
      commonSelector: '',
    })
  }

  const config = await prettier.resolveConfig(OUT_FILE)
  await writeFile(
    OUT_FILE,
    await prettier.format(css, { ...config, parser: 'css' }),
  )
  const iconCount = [...found.values()].reduce((n, s) => n + s.size, 0)
  console.log(
    `[generate-icons.ts] wrote ${OUT_FILE} (${iconCount} icons from ${found.size} sets)`,
  )
}

await main()
