import { glob, readFile, writeFile } from 'node:fs/promises'

import { getIconData, getIconsCSS } from '@iconify/utils'
import * as prettier from 'prettier'

const OUT_FILE = 'src/components/icon.css'
const SCAN_GLOB = 'src/**/*.{astro,ts,tsx,js,jsx}'

// Iconify's own class name convention, namespaced with `astrobook-`. The double
// hyphens split the icon set from the icon name, either of which may itself
// contain single hyphens ('fluent-emoji', 'chevron-down-16-regular').
const ICON_SELECTOR = '.astrobook-icon--{prefix}--{name}'
const ICON_CLASS =
  /astrobook-icon--([a-z\d]+(?:-[a-z\d]+)*)--([a-z\d]+(?:-[a-z\d]+)*)/g

// The comment must not contain the scan glob: its "**/*" would end the CSS
// comment early ("*/") and break the file.
const HEADER = `/*
 * Generated by generate-icons.ts. Do not edit by hand.
 *
 * This file styles every \`astrobook-icon--{set}--{name}\` class found in the
 * source files under src/, using icon data from the installed @iconify-json
 * packages. To update it (after adding, removing, or renaming an icon class,
 * or after an @iconify-json version bump), run:
 *
 *   pnpm --filter @astrobook/ui generate-icons
 */

`

type IconSet = Parameters<typeof getIconData>[0]

const setCache = new Map<string, IconSet | null>()

async function loadIconSet(set: string): Promise<IconSet | null> {
  let icons = setCache.get(set)
  if (icons === undefined) {
    try {
      const mod = (await import(`@iconify-json/${set}/icons.json`, {
        with: { type: 'json' },
      })) as { default: IconSet }
      icons = mod.default
    } catch {
      icons = null
    }
    setCache.set(set, icons)
  }
  return icons
}

async function main() {
  const exclude = (entry: string) => {
    return entry.includes('node_modules') || entry.endsWith('icon.css')
  }

  // "{set}--{name}" -> the source files using it, so errors can point at them.
  const usage = new Map<string, Set<string>>()
  for await (const file of glob(SCAN_GLOB, { exclude })) {
    const text = await readFile(file, 'utf8')
    for (const [, set, name] of text.matchAll(ICON_CLASS)) {
      const icon = `${set}--${name}`
      if (!usage.has(icon)) usage.set(icon, new Set())
      usage.get(icon)?.add(file)
    }
  }

  const found = new Map<string, { icons: IconSet; names: string[] }>()
  const errors: string[] = []
  // Sorted, so that both the icon sets and the icons within them come out in a
  // stable order.
  for (const icon of [...usage.keys()].sort()) {
    const [set, name] = icon.split('--')
    const files = [...(usage.get(icon) ?? [])].sort().join(', ')
    const icons = await loadIconSet(set)
    if (!icons) {
      errors.push(`"${icon}" (in ${files}): @iconify-json/${set} not installed`)
    } else if (!getIconData(icons, name)) {
      errors.push(
        `"${icon}" (in ${files}): @iconify-json/${set} has no "${name}"`,
      )
    } else {
      const entry = found.get(set) ?? { icons, names: [] }
      entry.names.push(name)
      found.set(set, entry)
    }
  }

  if (errors.length > 0) {
    throw new Error(
      [
        `Cannot resolve ${errors.length} icon class(es):`,
        ...errors,
        'Fix the icon name, or adjust the installed @iconify-json/* packages',
        'in the devDependencies of packages/ui.',
      ].join('\n'),
    )
  }

  let css = HEADER
  let iconCount = 0
  for (const { icons, names } of found.values()) {
    css += getIconsCSS(icons, names, {
      iconSelector: ICON_SELECTOR,
      commonSelector: '',
    })
    iconCount += names.length
  }

  const config = await prettier.resolveConfig(OUT_FILE)
  await writeFile(
    OUT_FILE,
    await prettier.format(css, { ...config, parser: 'css' }),
  )
  console.log(
    `[generate-icons.ts] wrote ${OUT_FILE} (${iconCount} icons from ${found.size} sets)`,
  )
}

await main()
