import path from 'node:path'

import type { Story, StoryModule } from '@astrobook/types'
import type { AstroIntegrationLogger } from 'astro'
import slash from 'slash'

import { invariant } from '../utils/invariant'
import type { PathBuilder } from '../utils/path-builder'

import { getStoryModules } from './get-story-modules'

export interface VirtualRoute {
  pattern: string
  /**
   * The absolute path to the virtual entrypoint file. Posix slash format.
   *
   * It's important to use an absolute path here because we must ensure that we
   * only have one `id`, so that Astro's CSS plugin can find the correct CSS
   * content in the following line.
   * https://github.com/withastro/astro/blob/bc2796436dc3810e988c27b71b7a66fcb1ae8bda/packages/astro/src/core/build/plugins/plugin-css.ts#L144
   */
  entrypoint: string
  storyModule: StoryModule
  story: Story
  props: {
    hasSidebar: boolean
    story: string
  }
}

export async function getVirtualRoutes(
  rootDir: string,
  codegenDir: string,
  logger: AstroIntegrationLogger,
  dashboardSubpath: string,
  previewSubpath: string,
  buildPath: PathBuilder,
): Promise<Map<string, VirtualRoute>> {
  const routes: VirtualRoute[] = []
  const storyModules = await getStoryModules(rootDir)

  for (const storyModule of storyModules) {
    logger.debug(
      `Found ${storyModule.stories.length} stories in ${storyModule.importPath}`,
    )
    for (const story of storyModule.stories) {
      invariant(
        !story.id.startsWith('..'),
        `Story ID cannot start with '..', but got '${story.id}'`,
      )
      invariant(
        !story.id.startsWith('/'),
        `Story ID cannot start with '/', but got '${story.id}'`,
      )
      routes.push(
        {
          pattern: buildPath(dashboardSubpath, story.id),
          entrypoint: slash(
            path.resolve(codegenDir, 'dashboard', story.id + '.astro'),
          ),
          storyModule,
          story,
          props: { hasSidebar: true, story: story.id },
        },
        {
          pattern: buildPath(previewSubpath, story.id),
          entrypoint: slash(
            path.resolve(codegenDir, 'stories', story.id + '.astro'),
          ),
          storyModule,
          story,
          props: { hasSidebar: false, story: story.id },
        },
      )
    }
  }

  logger.info(`Found ${routes.length} stories in ${storyModules.length} files`)

  return new Map(routes.map((route) => [route.pattern, route]))
}

export function createVirtualRouteComponent(route: VirtualRoute): string {
  return `
---
// Automatically generated by Astrobook

import StoryPage from 'astrobook/pages/story.astro';
import WithDecorators from 'astrobook/components/with-decorators.astro';
import { parseStoryDefaultExport, parseStoryNamedExport } from 'astrobook/client';

import * as mod from '${route.storyModule.importPath}';

const { isAstroComponent } = parseStoryDefaultExport(mod, '${route.storyModule.importPath}');
const { decorators, args, slots } = parseStoryNamedExport(mod, '${route.storyModule.importPath}', '${route.story.name}');
---

<StoryPage story={'${route.props.story}'} hasSidebar={${route.props.hasSidebar}}>
  <WithDecorators decorators={decorators}>
    {isAstroComponent ? (
      <mod.default.component {...args}>
        {slots?.default && (typeof slots.default === 'function' ? <slots.default /> : <Fragment set:html={slots.default} />)}
      </mod.default.component>
    ) : (
      <mod.default.component {...args} client:load>
        {args?.children || slots?.default}
      </mod.default.component>
    )}
  </WithDecorators>
</StoryPage>
`.trim()
}
