name: CI

on:
  push:
    branches:
      - master

  pull_request:
    branches:
      - master

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - uses: ./.github/actions/setup

      - name: Build
        run: pnpm run build

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - uses: ./.github/actions/setup

      - name: Lint
        run: pnpm run lint

      - name: Typecheck
        run: pnpm run typecheck

  test-unit:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - uses: ./.github/actions/setup

      - name: Test
        run: pnpm run test

  test-e2e:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        mode: [dev, preview]
        browser: [chromium, firefox, webkit]

    runs-on: ${{ matrix.os }}
    env:
      ASTROBOOK_TEST_MODE: ${{ matrix.mode }}

    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - uses: ./.github/actions/setup

      - name: Install Playwright
        run: pnpm run test:install:${{ matrix.browser }}

      - name: Build
        if: ${{ matrix.mode == 'preview' }}
        run: pnpm run build

      - name: Test
        run: pnpm run test:e2e -- --project=${{ matrix.browser }}
