name: CI

on:
  push:
    branches:
      - master

  pull_request:
    branches:
      - master

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3

      - uses: ./.github/actions/setup

      - uses: ./.github/actions/cache

      - name: Build
        run: pnpm run build

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3

      - uses: ./.github/actions/setup

      - name: Lint
        run: pnpm run lint

      - name: Typecheck
        run: pnpm run typecheck

  test-unit:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3

      - uses: ./.github/actions/setup

      - name: Test
        run: pnpm run test

  test-e2e:
    needs: build

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        mode: [dev, preview]
        browser: [chromium, firefox, webkit]
        exclude:
          - os: windows-latest
            browser: webkit

    runs-on: ${{ matrix.os }}
    env:
      ASTROBOOK_TEST_MODE: ${{ matrix.mode }}
      ASTROBOOK_TEST_BROWSER: ${{ matrix.browser }}

    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3

      - uses: ./.github/actions/setup

      - uses: ./.github/actions/cache

      - name: Install Playwright
        run: pnpm run test:install:${{ matrix.browser }}

      - name: Build
        if: ${{ matrix.mode == 'preview' }}
        run: pnpm run build

      - name: Test
        run: pnpm run test:e2e
