# https://autofix.ci/setup

name: autofix.ci

on:
  pull_request:

permissions:
  contents: read

jobs:
  fix:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: ./.github/actions/setup

      - name: Fix
        run: pnpm run fix

      - uses: autofix-ci/action@2891949f3779a1cafafae1523058501de3d4e944
